#pragma once

#include "Barbaro.hpp"
#include "Brujo.hpp"
#include "Caballero.hpp"
#include "Conjurador.hpp"
#include "Gladiador.hpp"
#include "Guerrero.hpp"
#include "Hechicero.hpp"
#include "Mago.hpp"
#include "Mercenario.hpp"
#include "Nigromante.hpp"
#include "Paladin.hpp"

#include "ArmaCombate.hpp"
#include "ArmaMagica.hpp"
#include "Baston.hpp"
#include "Espada.hpp"
#include "Garrote.hpp"
#include "HachaDoble.hpp"
#include "HachaSimple.hpp"
#include "Lanza.hpp"
#include "LibroHechizos.hpp"
#include "Pocion.hpp"
#include "Amuleto.hpp"

