#pragma once

#include "../EJ1/Barbaro.hpp"
#include "../EJ1/Brujo.hpp"
#include "../EJ1/Caballero.hpp"
#include "../EJ1/Conjurador.hpp"
#include "../EJ1/Gladiador.hpp"
#include "../EJ1/Guerrero.hpp"
#include "../EJ1/Hechicero.hpp"
#include "../EJ1/Mago.hpp"
#include "../EJ1/Mercenario.hpp"
#include "../EJ1/Nigromante.hpp"
#include "../EJ1/Paladin.hpp"

#include "../EJ1/ArmaCombate.hpp"
#include "../EJ1/ArmaMagica.hpp"
#include "../EJ1/Baston.hpp"
#include "../EJ1/Espada.hpp"
#include "../EJ1/Garrote.hpp"
#include "../EJ1/HachaDoble.hpp"
#include "../EJ1/HachaSimple.hpp"
#include "../EJ1/Lanza.hpp"
#include "../EJ1/LibroHechizos.hpp"
#include "../EJ1/Pocion.hpp"
#include "../EJ1/Amuleto.hpp"

